name: 'CI/CD'

run-name: '0.0.${{ github.run_number }} - ${{ github.workflow }}'

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  docker_build_push:
    uses: mars-office/.github/.github/workflows/docker.yaml@main
    secrets: inherit
    with:
      version: 'v0.0.${{ github.run_number }}'
  helm_build_push:
    uses: mars-office/.github/.github/workflows/helm.yaml@main
    secrets: inherit
    needs: [docker_build_push]
    with:
      version: '0.0.${{ github.run_number }}'
      workingDirectory: 'chart'
  snyk_container:
    uses: mars-office/.github/.github/workflows/snyk_container.yaml@main
    permissions:
      contents: read
      security-events: write
      actions: read
      packages: read
    secrets: inherit
    needs: [docker_build_push]
    with:
      version: 'v0.0.${{ github.run_number }}'
  snyk_iac:
    uses: mars-office/.github/.github/workflows/snyk_iac.yaml@main
    secrets: inherit
    needs: []