name: 'Docker Build and Push'

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths-ignore:
      - 'chart/templates/**'
      - 'chart/.helmignore'
      - 'chart/values.yaml'

  pull_request:
    branches:
      - main
    paths-ignore:
      - 'chart/**'

jobs:
  docker_build_push:
    uses: mars-office/.github/.github/workflows/docker.yaml@main
    secrets: inherit
