name: 'Docker/Helm Build and Push'

run-name: 'Docker/Helm Build and Push - 0.0.${{ github.run_number }}'

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  docker_build_push:
    uses: mars-office/.github/.github/workflows/docker.yaml@main
    secrets: inherit
    with:
      version: '0.0.${{ github.run_number }}'
  helm_build_push:
    uses: mars-office/.github/.github/workflows/helm.yaml@main
    secrets: inherit
    with:
      version: '0.0.${{ github.run_number }}'
      workingDirectory: 'chart'