name: 'Helm Build and Push'

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'chart/**'

  pull_request:
    branches:
      - main
    paths:
      - 'chart/**'

jobs:
  helm_build_push:
    uses: mars-office/.github/.github/workflows/helm.yaml@main
    secrets: inherit
    with:
      workingDirectory: 'chart'
